# Generated by Django 4.2.24 on 2025-09-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('usertype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registernumber', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('discription', models.CharField(blank=True, max_length=100, null=True)),
                ('patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('medicalreport', models.FileField(blank=True, null=True, upload_to='')),
                ('patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, max_length=100, null=True)),
                ('guardianid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.guardianmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('reply', models.CharField(blank=True, max_length=100, null=True)),
                ('guardianid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.guardianmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('Time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('medicineid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.medicinemodel')),
                ('patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PillDispenserApp.patientmodel')),
            ],
        ),
    ]
