# Generated by Django 4.2.26 on 2025-12-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PillDispenserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='date',
            field=models.DateField(auto_now_add=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
